# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'tarea.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(583, 484)
        self.actionAbir = QAction(MainWindow)
        self.actionAbir.setObjectName(u"actionAbir")
        self.actionGuardar = QAction(MainWindow)
        self.actionGuardar.setObjectName(u"actionGuardar")
        self.actionGrafo = QAction(MainWindow)
        self.actionGrafo.setObjectName(u"actionGrafo")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_3 = QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.gridLayout_4 = QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.tabla = QTableWidget(self.tab_2)
        self.tabla.setObjectName(u"tabla")

        self.gridLayout_4.addWidget(self.tabla, 0, 0, 1, 4)

        self.buscar_pushButton = QPushButton(self.tab_2)
        self.buscar_pushButton.setObjectName(u"buscar_pushButton")

        self.gridLayout_4.addWidget(self.buscar_pushButton, 1, 2, 1, 1)

        self.buscar_lineEdit = QLineEdit(self.tab_2)
        self.buscar_lineEdit.setObjectName(u"buscar_lineEdit")

        self.gridLayout_4.addWidget(self.buscar_lineEdit, 1, 0, 1, 2)

        self.id = QPushButton(self.tab_2)
        self.id.setObjectName(u"id")

        self.gridLayout_4.addWidget(self.id, 2, 1, 1, 1)

        self.velocidad = QPushButton(self.tab_2)
        self.velocidad.setObjectName(u"velocidad")

        self.gridLayout_4.addWidget(self.velocidad, 2, 2, 1, 1)

        self.distancia = QPushButton(self.tab_2)
        self.distancia.setObjectName(u"distancia")

        self.gridLayout_4.addWidget(self.distancia, 2, 3, 1, 1)

        self.mostrar_tabla_pushButton_2 = QPushButton(self.tab_2)
        self.mostrar_tabla_pushButton_2.setObjectName(u"mostrar_tabla_pushButton_2")

        self.gridLayout_4.addWidget(self.mostrar_tabla_pushButton_2, 1, 3, 1, 1)

        self.tabWidget.addTab(self.tab_2, "")
        self.bgh = QWidget()
        self.bgh.setObjectName(u"bgh")
        self.graphicsView = QGraphicsView(self.bgh)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(169, 90, 391, 271))
        self.dibujar = QPushButton(self.bgh)
        self.dibujar.setObjectName(u"dibujar")
        self.dibujar.setGeometry(QRect(230, 370, 101, 23))
        self.limpiar = QPushButton(self.bgh)
        self.limpiar.setObjectName(u"limpiar")
        self.limpiar.setGeometry(QRect(370, 370, 91, 23))
        self.groupBox = QGroupBox(self.bgh)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 0, 171, 381))
        self.id_lineEdit = QLineEdit(self.groupBox)
        self.id_lineEdit.setObjectName(u"id_lineEdit")
        self.id_lineEdit.setGeometry(QRect(30, 10, 133, 20))
        self.origeny_spinBox = QSpinBox(self.groupBox)
        self.origeny_spinBox.setObjectName(u"origeny_spinBox")
        self.origeny_spinBox.setGeometry(QRect(84, 62, 71, 20))
        self.origeny_spinBox.setMaximum(500)
        self.destinox_spinBox = QSpinBox(self.groupBox)
        self.destinox_spinBox.setObjectName(u"destinox_spinBox")
        self.destinox_spinBox.setGeometry(QRect(84, 88, 71, 20))
        self.destinox_spinBox.setMaximum(500)
        self.origenx_spinBox = QSpinBox(self.groupBox)
        self.origenx_spinBox.setObjectName(u"origenx_spinBox")
        self.origenx_spinBox.setGeometry(QRect(84, 36, 71, 20))
        self.origenx_spinBox.setMaximum(500)
        self.label_12 = QLabel(self.groupBox)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 62, 60, 16))
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 166, 56, 16))
        self.green_spinBox = QSpinBox(self.groupBox)
        self.green_spinBox.setObjectName(u"green_spinBox")
        self.green_spinBox.setGeometry(QRect(84, 211, 61, 20))
        self.green_spinBox.setMaximum(255)
        self.label_14 = QLabel(self.groupBox)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 36, 60, 16))
        self.label_15 = QLabel(self.groupBox)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 114, 49, 16))
        self.mostrar_pushButton = QPushButton(self.groupBox)
        self.mostrar_pushButton.setObjectName(u"mostrar_pushButton")
        self.mostrar_pushButton.setGeometry(QRect(10, 347, 131, 23))
        self.label_16 = QLabel(self.groupBox)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 10, 16, 16))
        self.red_spinBox = QSpinBox(self.groupBox)
        self.red_spinBox.setObjectName(u"red_spinBox")
        self.red_spinBox.setGeometry(QRect(84, 185, 61, 20))
        self.red_spinBox.setMaximum(255)
        self.destinoy_spinBox = QSpinBox(self.groupBox)
        self.destinoy_spinBox.setObjectName(u"destinoy_spinBox")
        self.destinoy_spinBox.setGeometry(QRect(84, 114, 71, 20))
        self.destinoy_spinBox.setMaximum(500)
        self.spinBox = QSpinBox(self.groupBox)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(84, 140, 71, 20))
        self.blue_spinBox = QSpinBox(self.groupBox)
        self.blue_spinBox.setObjectName(u"blue_spinBox")
        self.blue_spinBox.setGeometry(QRect(84, 237, 61, 20))
        self.blue_spinBox.setMaximum(255)
        self.label_17 = QLabel(self.groupBox)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 88, 49, 16))
        self.agregarinicio_pushButton = QPushButton(self.groupBox)
        self.agregarinicio_pushButton.setObjectName(u"agregarinicio_pushButton")
        self.agregarinicio_pushButton.setGeometry(QRect(10, 318, 131, 23))
        self.label_18 = QLabel(self.groupBox)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 140, 49, 16))
        self.label_19 = QLabel(self.groupBox)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 185, 19, 16))
        self.agregarfinal_pushButton = QPushButton(self.groupBox)
        self.agregarfinal_pushButton.setObjectName(u"agregarfinal_pushButton")
        self.agregarfinal_pushButton.setGeometry(QRect(10, 289, 131, 23))
        self.label_20 = QLabel(self.groupBox)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 237, 20, 16))
        self.label_21 = QLabel(self.groupBox)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 211, 32, 16))
        self.label_22 = QLabel(self.groupBox)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 263, 47, 16))
        self.distancia_doubleSpinBox = QDoubleSpinBox(self.groupBox)
        self.distancia_doubleSpinBox.setObjectName(u"distancia_doubleSpinBox")
        self.distancia_doubleSpinBox.setGeometry(QRect(84, 263, 61, 20))
        self.salida_2 = QPlainTextEdit(self.bgh)
        self.salida_2.setObjectName(u"salida_2")
        self.salida_2.setGeometry(QRect(170, 0, 391, 81))
        self.tabWidget.addTab(self.bgh, "")

        self.gridLayout_3.addWidget(self.tabWidget, 1, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 583, 21))
        self.menuArchivo = QMenu(self.menubar)
        self.menuArchivo.setObjectName(u"menuArchivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menuArchivo.addAction(self.actionAbir)
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionGrafo)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionAbir.setText(QCoreApplication.translate("MainWindow", u"Abir", None))
#if QT_CONFIG(shortcut)
        self.actionAbir.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionGuardar.setText(QCoreApplication.translate("MainWindow", u"Guardar ", None))
#if QT_CONFIG(shortcut)
        self.actionGuardar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionGrafo.setText(QCoreApplication.translate("MainWindow", u"Grafo", None))
#if QT_CONFIG(shortcut)
        self.actionGrafo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.buscar_pushButton.setText(QCoreApplication.translate("MainWindow", u"Buscar", None))
        self.buscar_lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Id", None))
        self.id.setText(QCoreApplication.translate("MainWindow", u"Id", None))
        self.velocidad.setText(QCoreApplication.translate("MainWindow", u"Velocidad", None))
        self.distancia.setText(QCoreApplication.translate("MainWindow", u"Distancia", None))
        self.mostrar_tabla_pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Mostrar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Tabla", None))
        self.dibujar.setText(QCoreApplication.translate("MainWindow", u"Dibujar", None))
        self.limpiar.setText(QCoreApplication.translate("MainWindow", u"Limpiar", None))
        self.groupBox.setTitle("")
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Origen de y:", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Color(rgb): ", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Origen en x:", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Destino y:", None))
        self.mostrar_pushButton.setText(QCoreApplication.translate("MainWindow", u"Mostrar", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Id:", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Destino x:", None))
        self.agregarinicio_pushButton.setText(QCoreApplication.translate("MainWindow", u"Agregar inicio", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Velocidad:", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Red", None))
        self.agregarfinal_pushButton.setText(QCoreApplication.translate("MainWindow", u"Agregar final", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Blue", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Green ", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Distancia:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bgh), QCoreApplication.translate("MainWindow", u"Grafica", None))
        self.menuArchivo.setTitle(QCoreApplication.translate("MainWindow", u"Archivo ", None))
    # retranslateUi

