# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'tarea.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(763, 604)
        self.actionAbir = QAction(MainWindow)
        self.actionAbir.setObjectName(u"actionAbir")
        self.actionGuardar = QAction(MainWindow)
        self.actionGuardar.setObjectName(u"actionGuardar")
        self.actionGrafo = QAction(MainWindow)
        self.actionGrafo.setObjectName(u"actionGrafo")
        self.actionProfundidad = QAction(MainWindow)
        self.actionProfundidad.setObjectName(u"actionProfundidad")
        self.actionAmplitud = QAction(MainWindow)
        self.actionAmplitud.setObjectName(u"actionAmplitud")
        self.actionMuestra_de_amplitud_y_profundidad = QAction(MainWindow)
        self.actionMuestra_de_amplitud_y_profundidad.setObjectName(u"actionMuestra_de_amplitud_y_profundidad")
        self.actionRecorrido = QAction(MainWindow)
        self.actionRecorrido.setObjectName(u"actionRecorrido")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_3 = QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.gridLayout_4 = QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.tabla = QTableWidget(self.tab_2)
        self.tabla.setObjectName(u"tabla")

        self.gridLayout_4.addWidget(self.tabla, 0, 0, 1, 4)

        self.buscar_pushButton = QPushButton(self.tab_2)
        self.buscar_pushButton.setObjectName(u"buscar_pushButton")

        self.gridLayout_4.addWidget(self.buscar_pushButton, 1, 2, 1, 1)

        self.buscar_lineEdit = QLineEdit(self.tab_2)
        self.buscar_lineEdit.setObjectName(u"buscar_lineEdit")

        self.gridLayout_4.addWidget(self.buscar_lineEdit, 1, 0, 1, 2)

        self.id = QPushButton(self.tab_2)
        self.id.setObjectName(u"id")

        self.gridLayout_4.addWidget(self.id, 2, 1, 1, 1)

        self.velocidad = QPushButton(self.tab_2)
        self.velocidad.setObjectName(u"velocidad")

        self.gridLayout_4.addWidget(self.velocidad, 2, 2, 1, 1)

        self.distancia = QPushButton(self.tab_2)
        self.distancia.setObjectName(u"distancia")

        self.gridLayout_4.addWidget(self.distancia, 2, 3, 1, 1)

        self.mostrar_tabla_pushButton_2 = QPushButton(self.tab_2)
        self.mostrar_tabla_pushButton_2.setObjectName(u"mostrar_tabla_pushButton_2")

        self.gridLayout_4.addWidget(self.mostrar_tabla_pushButton_2, 1, 3, 1, 1)

        self.tabWidget.addTab(self.tab_2, "")
        self.bgh = QWidget()
        self.bgh.setObjectName(u"bgh")
        self.graphicsView = QGraphicsView(self.bgh)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(300, 10, 431, 461))
        self.dibujar = QPushButton(self.bgh)
        self.dibujar.setObjectName(u"dibujar")
        self.dibujar.setGeometry(QRect(550, 480, 75, 23))
        self.limpiar = QPushButton(self.bgh)
        self.limpiar.setObjectName(u"limpiar")
        self.limpiar.setGeometry(QRect(630, 480, 75, 23))
        self.label_22 = QLabel(self.bgh)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 270, 47, 16))
        self.distancia_doubleSpinBox = QDoubleSpinBox(self.bgh)
        self.distancia_doubleSpinBox.setObjectName(u"distancia_doubleSpinBox")
        self.distancia_doubleSpinBox.setGeometry(QRect(90, 270, 49, 20))
        self.agregarfinal_pushButton = QPushButton(self.bgh)
        self.agregarfinal_pushButton.setObjectName(u"agregarfinal_pushButton")
        self.agregarfinal_pushButton.setGeometry(QRect(380, 480, 75, 23))
        self.agregarinicio_pushButton = QPushButton(self.bgh)
        self.agregarinicio_pushButton.setObjectName(u"agregarinicio_pushButton")
        self.agregarinicio_pushButton.setGeometry(QRect(290, 480, 75, 23))
        self.mostrar_pushButton = QPushButton(self.bgh)
        self.mostrar_pushButton.setObjectName(u"mostrar_pushButton")
        self.mostrar_pushButton.setGeometry(QRect(470, 480, 75, 23))
        self.groupBox = QGroupBox(self.bgh)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 0, 261, 51))
        self.label_16 = QLabel(self.groupBox)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(40, 20, 41, 20))
        self.id_lineEdit = QLineEdit(self.groupBox)
        self.id_lineEdit.setObjectName(u"id_lineEdit")
        self.id_lineEdit.setGeometry(QRect(100, 20, 141, 16))
        self.groupBox_2 = QGroupBox(self.bgh)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 60, 261, 51))
        self.label_14 = QLabel(self.groupBox_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 20, 16, 16))
        self.origenx_spinBox = QSpinBox(self.groupBox_2)
        self.origenx_spinBox.setObjectName(u"origenx_spinBox")
        self.origenx_spinBox.setGeometry(QRect(40, 20, 61, 20))
        self.origenx_spinBox.setMaximum(500)
        self.label_12 = QLabel(self.groupBox_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(160, 20, 16, 16))
        self.origeny_spinBox = QSpinBox(self.groupBox_2)
        self.origeny_spinBox.setObjectName(u"origeny_spinBox")
        self.origeny_spinBox.setGeometry(QRect(190, 20, 51, 20))
        self.origeny_spinBox.setMaximum(500)
        self.groupBox_3 = QGroupBox(self.bgh)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 110, 261, 51))
        self.label_17 = QLabel(self.groupBox_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 20, 21, 16))
        self.destinox_spinBox = QSpinBox(self.groupBox_3)
        self.destinox_spinBox.setObjectName(u"destinox_spinBox")
        self.destinox_spinBox.setGeometry(QRect(50, 20, 61, 20))
        self.destinox_spinBox.setMaximum(500)
        self.label_15 = QLabel(self.groupBox_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(160, 20, 21, 16))
        self.destinoy_spinBox = QSpinBox(self.groupBox_3)
        self.destinoy_spinBox.setObjectName(u"destinoy_spinBox")
        self.destinoy_spinBox.setGeometry(QRect(190, 20, 51, 20))
        self.destinoy_spinBox.setMaximum(500)
        self.groupBox_4 = QGroupBox(self.bgh)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 160, 261, 51))
        self.label_18 = QLabel(self.groupBox_4)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(70, 20, 49, 16))
        self.spinBox = QSpinBox(self.groupBox_4)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(110, 20, 131, 20))
        self.groupBox_5 = QGroupBox(self.bgh)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(0, 220, 271, 51))
        self.label_19 = QLabel(self.groupBox_5)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 20, 19, 16))
        self.red_spinBox = QSpinBox(self.groupBox_5)
        self.red_spinBox.setObjectName(u"red_spinBox")
        self.red_spinBox.setGeometry(QRect(40, 20, 39, 20))
        self.red_spinBox.setMaximum(255)
        self.label_21 = QLabel(self.groupBox_5)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(100, 20, 32, 16))
        self.green_spinBox = QSpinBox(self.groupBox_5)
        self.green_spinBox.setObjectName(u"green_spinBox")
        self.green_spinBox.setGeometry(QRect(140, 20, 39, 20))
        self.green_spinBox.setMaximum(255)
        self.label_20 = QLabel(self.groupBox_5)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(190, 20, 20, 16))
        self.blue_spinBox = QSpinBox(self.groupBox_5)
        self.blue_spinBox.setObjectName(u"blue_spinBox")
        self.blue_spinBox.setGeometry(QRect(220, 20, 39, 20))
        self.blue_spinBox.setMaximum(255)
        self.groupBox_6 = QGroupBox(self.bgh)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(0, 290, 281, 221))
        self.salida_2 = QPlainTextEdit(self.groupBox_6)
        self.salida_2.setObjectName(u"salida_2")
        self.salida_2.setGeometry(QRect(10, 20, 261, 191))
        self.tabWidget.addTab(self.bgh, "")

        self.gridLayout_3.addWidget(self.tabWidget, 1, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 763, 21))
        self.menuArchivo = QMenu(self.menubar)
        self.menuArchivo.setObjectName(u"menuArchivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menuArchivo.addAction(self.actionAbir)
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionGrafo)
        self.menuArchivo.addAction(self.actionRecorrido)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionAbir.setText(QCoreApplication.translate("MainWindow", u"Abir", None))
#if QT_CONFIG(shortcut)
        self.actionAbir.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionGuardar.setText(QCoreApplication.translate("MainWindow", u"Guardar ", None))
#if QT_CONFIG(shortcut)
        self.actionGuardar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionGrafo.setText(QCoreApplication.translate("MainWindow", u"Grafo", None))
#if QT_CONFIG(shortcut)
        self.actionGrafo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionProfundidad.setText(QCoreApplication.translate("MainWindow", u"Busqueda de Profundidad", None))
#if QT_CONFIG(shortcut)
        self.actionProfundidad.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.actionAmplitud.setText(QCoreApplication.translate("MainWindow", u"Busqueda de Amplitud", None))
#if QT_CONFIG(shortcut)
        self.actionAmplitud.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionMuestra_de_amplitud_y_profundidad.setText(QCoreApplication.translate("MainWindow", u"Muestra de amplitud y profundidad ", None))
        self.actionRecorrido.setText(QCoreApplication.translate("MainWindow", u"Muestra de Amplitud y Profundidad ", None))
#if QT_CONFIG(shortcut)
        self.actionRecorrido.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.buscar_pushButton.setText(QCoreApplication.translate("MainWindow", u"Buscar", None))
        self.buscar_lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Id", None))
        self.id.setText(QCoreApplication.translate("MainWindow", u"Id", None))
        self.velocidad.setText(QCoreApplication.translate("MainWindow", u"Velocidad", None))
        self.distancia.setText(QCoreApplication.translate("MainWindow", u"Distancia", None))
        self.mostrar_tabla_pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Mostrar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Tabla", None))
        self.dibujar.setText(QCoreApplication.translate("MainWindow", u"Dibujar", None))
        self.limpiar.setText(QCoreApplication.translate("MainWindow", u"Limpiar", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Distancia:", None))
        self.agregarfinal_pushButton.setText(QCoreApplication.translate("MainWindow", u"Agregar final", None))
        self.agregarinicio_pushButton.setText(QCoreApplication.translate("MainWindow", u"Agregar inicio", None))
        self.mostrar_pushButton.setText(QCoreApplication.translate("MainWindow", u"Mostrar", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u" Particulas ", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Id:", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u" Origen", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u" X:", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u" Y:", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Destino ", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"X:", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Y:", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Velocidad", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Vel:", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Color (rgb):", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Red", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Green ", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Blue", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Salida:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bgh), QCoreApplication.translate("MainWindow", u"Grafica", None))
        self.menuArchivo.setTitle(QCoreApplication.translate("MainWindow", u"Archivo ", None))
    # retranslateUi

